### ISSUE TITLE
About ILS-CC and ILS- RCC

### ISSUE THREAD

**Issue by hotchilipowder** [israelzinc/netvotes#1]
Hello,  I am reading your [paper](https://arxiv.org/abs/1712.10157). Because I am not good at R, I have some questions about the code.  

In the paper, it said "We apply both ILS procedures in order to identify structural balanced partitions in each extracted signed network". I browsed the project branch V2. In [detect-clusters.R](https://github.com/CompNet/NetVotes/blob/v2/src/partition-networks/detect-clusters.R) , it use the community detection algorithm in igraph but I don't find the algorithm? Do I understand it correctly? May I get some  ILS algorithm implement details? 

thx a lot!

**Comment by vlabatut** [comment]
Hello,
and thanks for your interest!

Both ILS procedures were implemented in C++ by a collaborator (not a co-author on this paper though) who doesn't want to publish his source code under an open source license (at least for now). For this reason, this repository contains only our R source code, which is basically doing all the rest of the processing. At some point, we might include ILS in a subsequent version, but I cannot guarantee it, as it doesn't depend on me.

**Comment by hotchilipowder** [comment]
Yes, I read the [paper](https://link.springer.com/article/10.1007%2Fs13675-017-0082-6) you cited, it said "The algorithms described in the previous section were implemented in ANSI C++ and MPI (OpenMPI) for message passing".  But it seems that the authors don't open source code in the paper. 

Actually, I am doing something like the signed graph analysis you did it in your paper, I want to compare it to other algorithms. So may I get some information about the codes ? Or need I rewrite it by myself?

**Comment by vlabatut** [comment]
Indeed, as I said in my previous message, the author of the source code does not want to open it as of now. We could use it for our own paper because as you may have noticed, one of the authors appear in both paper (R. Figueiredo). But we can't share it. 

I'd avise you to directly contact the person that wrote this source code (Mario Levorato): He might share it with you.

**Comment by hotchilipowder** [comment]
I get it.  = = I recognize the same author just now. 
Thx a lot!
